DATA_DIR = "data"
PROCESSED_DIR = "processed"
TARGET = "late_response"
NON_PREDICTORS = [
            TARGET,
    'index',
    'AFD Time Phone Pickup',
    'Master Incident Number',
    'CalendarYear',
    'Cancellation Status',
    'General Dispatched Problem ',
    'Calltaker Agency (AFD or EMS)',
    'Order of AFD Arrival',
    'Response Area (COA Only)',
    'First Arriving Unit Name',
    'Response Status',
    'PriorityDescription',
    'EMS Time Phone Pickup',
    'Earliest Time Phone Pickup',
    'First Unit Assigned',
    'Did not Reduce to Code 1',
    'Onscene Time Was Correct',
    'Latitude',
    'Longitude',
    'First Unit Enroute',
    'First Unit Arrived',
    'Response Time (s)',
    'Response Time (m)',
    'Month',
    'DayOfMonth',
    'Call_Type',
    'Battalion',
    'Jurisdiction',
    'Districts',
    'Location 1',
    'late_response']

